affirmation_set = {
    "I alone hold the truth of who I am.",
    "Asking for help is a sign of self-respect and self-awareness.",
    "Changing my mind is a strength, not a weakness.",
    "Every decision I make is supported by my whole and inarguable experience.",
    "I affirm and encourage others, as I do myself.",
    "I alone hold the truth of who I am.",
    "I am capable of balancing ease and effort in my life.",
    "I am complete as I am, others simply support me.",
    "I am growing and I am going at my own pace.",
    "I am doing the work that works for me.",
    "I am good and getting better.",
    "I am growing and I am going at my own pace.",
    "I am held and supported by those who love me.",
    "I am in charge of how I feel and I choose to feel happy.",
    "I am listening and open to the messages the universe has to offer today.",
    "I am more than my circumstances dictate.",
    "I am optimistic because today is a new day.",
    "I am proof enough of who I am and what I deserve.",
    "I am proof enough of who I am and what I deserve.",
    "I am responsible for myself, and I start there.",
    "I am safe and surrounded by love and support.",
    "I am still learning so it’s okay to make mistakes.",
    "I am understood and my perspective is important.",
    "I am well-rested and excited for the day.",
    "I belong here, and I deserve to take up space.",
    "I breathe in healing, I exhale the painful things that burden my heart.",
    "I can hold two opposing feelings at once, it means I am processing.",
    "I can be soft in my heart and firm in my boundaries.",
    "I can control how I respond to things that are confronting.",
    "I can hold two opposing feelings at once, it means I am processing.",
    "I do not have to linger in dark places; there is help for me here.",
    "I do not pretend to be anyone or anything other than who I am.",
    "I do not rise and fall for another.",
    "I do not rush through my life, I temper speed with stillness.",
    "I embrace change seamlessly and rise to the new opportunity it presents.",
    "I embrace the questions in my heart and welcome the answers in their own time.",
    "I grow towards my interests, like a plant reaching for the sun.",
    "I have come farther than I would have ever thought possible, and I’m learning along the way.",
    "I have everything I need to succeed.",
    "I hold community for others, and am held in community by others.",
    "I hold wisdom beyond knowledge.",
    "I invite abundance and a generous heart.",
    "I invite art and music into my life.",
    "I leave room in my life for spontaneity.",
    "I let go of the things that sit achingly out of reach.",
    "I look forward to tomorrow and the opportunities that await me.",
    "I make decisions based on a good gut, I make changes based on a growing heart.",
    "I make time to experience grief and sadness when necessary.",
    "I nourish myself with kind words and joyful foods.",
    "I practice gratitude for all that I have, and all that is yet to come.",
    "I release the fears that do not serve me.",
    "I respect the cycle of the seasons.",
    "I seek out mystery in the ordinary.",
    "I strive for joy, not for perfection.",
    "I tell the truth about who I am and what I need from others.",
    "I uplift my joy and the joy of others.",
    "I welcome the wisdom that comes with growing older.",
    "Letting go creates space for opportunities to come.",
    "My body is beautiful in this moment and at its current size.",
    "My body is worthy of being cared for and adorned in beautiful garments.",
    "My feelings deserve names, deserve recognition, deserve to be felt.",
    "My heart is open to helpfulness from myself and from others.",
    "My heart knows its own way.",
    "My life is not a race or competition.",
    "My perspective is unique and important.",
    "My pleasure does not require someone else’s pain.",
    "My sensitivity is beautiful, and my feelings and emotions are valid.",
    "My weirdness is wonderful.",
    "Saying “no” is an act of self-affirmation, too.",
    "Sometimes the work is resting.",
    "There is growth in stillness.",
    "There is peace in changing your mind when it is done in love.",
    "There is poetry in everything, if I look for it.",
    "There is room for me at the table.",
    "There is something in this world that only I can do. That is why I am here.",
    "Today I celebrate that I am younger than I’m ever going to be.",
    "Today is an opportunity to grow and learn.",
    "When I focus on my reason for being, I am infinitely brave.",
    "When I forgive myself, I free myself.",
    "When I release shame, I move into myself more beautifully.",
    "When I root into the earth, the earth rises to support me.",
    "When I speak my needs, I receive them abundantly.",
    "When I talk to myself as I would a friend, I see all my best qualities and I allow myself to shine.",
    "Words may shape me, but they do not make me. I am here already."
    "My mind and my body are ready to start the day. I am focused, centered and at peace. Everything will be okay!",
    "I am grateful for today, for my mind and for my body. I look forward to overcoming and thriving.",
    "Today, I’m the best version of myself. I am ready to achieve my goals. A new day means a new opportunity.",
    "My mind is a place for hope and positivity. I believe in myself. I’ll achieve, I’ll conquer, and I’ll succeed today.",
    "Living my best and being my best is a natural state for me. My mind and my body are recharged. I’ll enjoy this day fully.",
    "I’m grateful, at ease, fearless, and brave. I control my mind. I have all the power.",
    "I’m thankful for this life, for this heart, for this body, and for this mind. They are worthy and they are mine.",
    "Calming thoughts, self-love, optimism, and success will fill this day. I’ll create a safe space for myself today and every day.",
    "I will let every worry go. Learn from the past and focus on moving forward. My mind is strong and capable, my body is my own, and I am deserving of a good day.",
    "I am thankful for this day, grateful for the new opportunities, and looking forward to excelling.",
    "Worries, stress, outside and internal pressures can’t control me. I will be at peace, let go, and be kind to myself. I’m worthy of achieving my dreams and deserving of great things.",
    "I love and accept this mind and this body. I will nourish and cherish them through loving thoughts, today and always.",
    "I am thankful for the endless opportunities that will come my way today. I am ready. My goals are always possible.",
    "I breathe, I live, and I feel myself more at ease with every breath I take. I deserve good things. Today I’ll receive the things I dream about.",
    "Today is a good day. The universe is at peace with me and I’m embracing the universe. Great things will come.",
    "I choose life, love, peace, prosperity, and abundance over gloominess, stress, worry, and apprehension.",
    "My mindfulness and wellness are my priorities.",
    "I will be proud of myself today. Not with disdain towards others, but with deserving self-love and self-respect. I am a beautiful being.",
    "I am worthy and I am dreaming. My dreams will become a reality.",
    "I choose to stop worrying, stressing, and dwelling on negativity. I am in a natural wellness state. My body deserves a good day.",
    "I am healthy and capable of thanking my body with a day full of joy and accomplishments.",
    "My mind and my body are ready to shine today.",
    "I am in control of my mind, my emotions, and my whole self. I can always create a safe place for myself.",
    "I’m confident in my abilities to succeed and achieve today.",
    "Today I will choose kindness and love. I’ll be good to myself. My soul, my mind, and my body are beautiful. I will attract loving thoughts, prosperity, and success.",
    "I’m enough, I’m worthy, and I heal through the power of these words. Yesterday is no longer a burden but a lesson. Today is a gift. I will receive it. Nothing can hold me back.",
    "I welcome a peaceful, prosperous, and gentle day. With these breaths and these words, I relieve my body and my mind of all anxiety and stress.",
    "My mind is in synchronization with the natural state of the universe. Today I’m relaxed and I will live to achieve.",
    "With these thoughts and these breaths, my eyes are opening effortlessly to a world of endless mental wealth and abundance. I’ll enjoy everything that comes my way today.",
    "My mind has the power to defeat my fears, to overcome my anxiety, and to erase my doubts. I can now confidently start my day. I’m confident and capable.",
    "I am not defined by past mistakes. I am up and awake. No matter what, I am worthy of today.",
    "I deserve life, I deserve love, I deserve peace. Today is my day!",
    "I’m living, I’m learning, and I’m growing. I’m present this morning and I’ll continue to be present all throughout this day. I believe in myself."
}
