#this is in order 
bible_verses = [
    {"reference": "John 3:16", "verse": "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", "version": "NIV", "hashtag": "#John3_16"},
    {"reference": "John 1:1", "verse": "In the beginning was the Word, and the Word was with God, and the Word was God.", "version": "NIV", "hashtag": "#John1_1"},
    {"reference": "John 14:6", "verse": "Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'", "version": "NIV", "hashtag": "#John14_6"},
    {"reference": "Matthew 28:19", "verse": "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit.", "version": "NIV", "hashtag": "#Matt28_19"},
    {"reference": "Romans 3:23", "verse": "For all have sinned and fall short of the glory of God.", "version": "NIV", "hashtag": "#Rom3_23"},
    {"reference": "Ephesians 2:8", "verse": "For it is by grace you have been saved, through faith – and this is not from yourselves, it is the gift of God.", "version": "NIV", "hashtag": "#Eph2_8"},
    {"reference": "Genesis 1:1", "verse": "In the beginning God created the heavens and the earth.", "version": "NIV", "hashtag": "#Gen1_1"},
    {"reference": "Acts 1:8", "verse": "'But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.'", "version": "NIV", "hashtag": "#Acts1_8"},
    {"reference": "2 Timothy 3:16", "verse": "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.", "version": "NIV", "hashtag": "#IITim3_16"},
    {"reference": "Romans 10:9", "verse": "If you declare with your mouth, 'Jesus is Lord,' and believe in your heart that God raised him from the dead, you will be saved.", "version": "NIV", "hashtag": "#Rom10_9"},
    {"reference": "Romans 6:23", "verse": "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", "version": "NIV", "hashtag": "#Rom6_23"},
    {"reference": "Acts 2:38", "verse": "Peter replied, 'Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.'", "version": "NIV", "hashtag": "#Acts2_38"},
    {"reference": "John 1:12", "verse": "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God.", "version": "NIV", "hashtag": "#John1_12"},
    {"reference": "Romans 8:28", "verse": "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", "version": "NIV", "hashtag": "#Rom8_28"},
    {"reference": "John 1:9", "verse": "The true light that gives light to everyone was coming into the world.", "version": "NIV", "hashtag": "#John1_9"},
    {"reference": "Genesis 1:26", "verse": "Then God said, 'Let us make human beings in our image, in our likeness, so that they may rule over the fish in the sea and the birds in the sky, over the livestock and all the wild animals, and over all the creatures that move along the ground.'", "version": "NIV", "hashtag": "#Gen1_26"},
    {"reference": "Romans 12:1", "verse": "Therefore, I urge you, brothers and sisters, in view of God's mercy, to offer your bodies as a living sacrifice, holy and pleasing to God – this is true worship.", "version": "NIV", "hashtag": "#Rom12_1"},
    {"reference": "Romans 5:8", "verse": "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.", "version": "NIV", "hashtag": "#Rom5_8"},
    {"reference": "Matthew 28:18", "verse": "Then Jesus came to them and said, 'All authority in heaven and on earth has been given to me.'", "version": "NIV", "hashtag": "#Matt28_18"},
    {"reference": "John 3:3", "verse": "Jesus replied, 'Very truly I tell you, no one can see the kingdom of God without being born again.'", "version": "NIV", "hashtag": "#John3_3"},
    {"reference": "Mark 16:15", "verse": "He said to them, 'Go into all the world and preach the gospel to all creation.'", "version": "NIV", "hashtag": "#Mark16_15"},
    {"reference": "John 10:10", "verse": "The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.", "version": "NIV", "hashtag": "#John10_10"},
    {"reference": "John 1:14", "verse": "The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth.", "version": "NIV", "hashtag": "#John1_14"},
    {"reference": "Acts 4:12", "verse": "'Salvation is found in no one else, for there is no other name given under heaven by which we must be saved.'", "version": "NIV", "hashtag": "#Acts4_12"},
    {"reference": "Acts 2:42", "verse": "They devoted themselves to the apostles' teaching and to fellowship, to the breaking of bread and to prayer.", "version": "NIV", "hashtag": "#Acts2_42"},
    {"reference": "Titus 3:5", "verse": "He saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit.", "version": "NIV", "hashtag": "#Titus3_5"},
    {"reference": "Romans 12:2", "verse": "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is – his good, pleasing and perfect will.", "version": "NIV", "hashtag": "#Rom12_2"},
    {"reference": "John 14:1", "verse": "'Do not let your hearts be troubled. Trust in God; trust also in me.'", "version": "NIV", "hashtag": "#John14_1"},
    {"reference": "John 4:1", "verse": "Now Jesus learned that the Pharisees had heard that he was gaining and baptizing more disciples than John.", "version": "NIV", "hashtag": "#John4_1"},
    {"reference": "Ephesians 4:11", "verse": "So Christ himself gave the apostles, the prophets, the evangelists, the pastors and teachers.", "version": "NIV", "hashtag": "#Eph4_11"},
    {"reference": "Romans 5:12", "verse": "Therefore, just as sin entered the world through one man, and death through sin, and in this way death came to all people, because all sinned.", "version": "NIV", "hashtag": "#Rom5_12"},
    {"reference": "Matthew 11:28", "verse": "'Come to me, all you who are weary and burdened, and I will give you rest.'", "version": "NIV", "hashtag": "#Matt11_28"},
    {"reference": "Romans 5:1", "verse": "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ.", "version": "NIV", "hashtag": "#Rom5_1"},
    {"reference": "Genesis 1:27", "verse": "So God created human beings in his own image, in the image of God he created them; male and female he created them.", "version": "NIV", "hashtag": "#Gen1_27"},
    {"reference": "Romans 1:16", "verse": "'I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes: first to the Jew, then to the Gentile.'", "version": "NIV", "hashtag": "#Rom1_16"},
    {"reference": "1 John 1:9", "verse": "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.", "version": "NIV", "hashtag": "#IJn1_9"},
    {"reference": "Acts 2:1", "verse": "When the day of Pentecost came, they were all together in one place.", "version": "NIV", "hashtag": "#Acts2_1"},
    {"reference": "2 Corinthians 5:17", "verse": "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", "version": "NIV", "hashtag": "#IICor5_17"},
    {"reference": "Hebrews 11:1", "verse": "'Now faith is being sure of what we hope for and certain of what we do not see.'", "version": "NIV", "hashtag": "#Heb11_1"},
    {"reference": "2 Timothy 2:15", "verse": "Do your best to present yourself to God as one approved, a worker who does not need to be ashamed and who correctly handles the word of truth.", "version": "NIV", "hashtag": "#IITim2_15"},
    {"reference": "Romans 8:1", "verse": "'Therefore, there is now no condemnation for those who are in Christ Jesus.'", "version": "NIV", "hashtag": "#Rom8_1"},
    {"reference": "Romans 10:13", "verse": "For, 'Everyone who calls on the name of the Lord will be saved.'", "version": "NIV", "hashtag": "#Rom10_13"},
    {"reference": "John 8:32", "verse": "'Then you will know the truth, and the truth will set you free.'", "version": "NIV", "hashtag": "#John8_32"},
    {"reference": "Isaiah 9:6", "verse": "For to us a child is born, to us a son is given, and the government will be on his shoulders. And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.", "version": "NIV", "hashtag": "#Isa9_6"},
    {"reference": "John 14:15", "verse": "'If you love me, keep my commands.'", "version": "NIV", "hashtag": "#John14_15"},
    {"reference": "Deuteronomy 6:4", "verse": "'Hear, O Israel: The LORD our God, the LORD is one.'", "version": "NIV", "hashtag": "#Deut6_4"},
    {"reference": "John 13:34", "verse": "'A new command I give you: Love one another. As I have loved you, so you must love one another.'", "version": "NIV", "hashtag": "#John13_34"},
    {"reference": "John 4:24", "verse": "'God is spirit, and his worshipers must worship in the Spirit and in truth.'", "version": "NIV", "hashtag": "#John4_24"},
    {"reference": "Philippians 4:13", "verse": "'I can do all this through him who gives me strength.'", "version": "NIV", "hashtag": "#Phil4_13"},
    {"reference": "Ephesians 2:1", "verse": "As for you, you were dead in your transgressions and sins.", "version": "NIV", "hashtag": "#Eph2_1"},
    {"reference": "John 14:16", "verse": "'And I will ask the Father, and he will give you another advocate to help you and be with you forever.'", "version": "NIV", "hashtag": "#John14_16"},
    {"reference": "Genesis 1:2", "verse": "Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.", "version": "NIV", "hashtag": "#Gen1_2"},
    {"reference": "Matthew 22:37", "verse": "Jesus replied: 'Love the Lord your God with all your heart and with all your soul and with all your mind.'", "version": "NIV", "hashtag": "#Matt22_37"},
    {"reference": "Titus 2:13", "verse": "While we wait for the blessed hope – the appearing of the glory of our great God and Savior, Jesus Christ", "version": "NIV", "hashtag": "#Titus2_13"},
    {"reference": "Philippians 4:8", "verse": "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable – if anything is excellent or praiseworthy – think about such things.", "version": "NIV", "hashtag": "#Phil4_8"},
    {"reference": "Acts 1:9", "verse": "After he said this, he was taken up before their very eyes, and a cloud hid him from their sight.", "version": "NIV", "hashtag": "#Acts1_9"},
    {"reference": "John 4:7", "verse": "When a Samaritan woman came to draw water, Jesus said to her, 'Will you give me a drink?'", "version": "NIV", "hashtag": "#John4_7"},
    {"reference": "Micah 6:8", "verse": "He has shown all you people what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.", "version": "NIV", "hashtag": "#Mic6_8"},
    {"reference": "John 17:17", "verse": "Sanctify them by the truth; your word is truth.", "version": "NIV", "hashtag": "#John17_17"},
    {"reference": "Leviticus 18:22", "verse": "'Do not have sexual relations with a man as one does with a woman; that is detestable.'", "version": "NIV", "hashtag": "#Lev18_22"},
    {"reference": "Acts 20:7", "verse": "On the first day of the week we came together to break bread. Paul spoke to the people and, because he intended to leave the next day, kept on talking until midnight.", "version": "NIV", "hashtag": "#Acts20_7"},
    {"reference": "Acts 16:31", "verse": "They replied, 'Believe in the Lord Jesus, and you will be saved – you and your household.'", "version": "NIV", "hashtag": "#Acts16_31"},
    {"reference": "John 11:25", "verse": "Jesus said to her, 'I am the resurrection and the life. Anyone who believes in me will live, even though they die;'", "version": "NIV", "hashtag": "#John11_25"},
    {"reference": "John 8:58", "verse": "'Very truly I tell you,' Jesus answered, 'before Abraham was born, I am!'", "version": "NIV", "hashtag": "#John8_58"},
    {"reference": "Acts 2:4", "verse": "All of them were filled with the Holy Spirit and began to speak in other tongues as the Spirit enabled them.", "version": "NIV", "hashtag": "#Acts2_4"},
    {"reference": "John 15:5", "verse": "'I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.'", "version": "NIV", "hashtag": "#John15_5"},
    {"reference": "Acts 2:41", "verse": "Those who accepted his message were baptized, and about three thousand were added to their number that day.", "version": "NIV", "hashtag": "#Acts2_41"},
    {"reference": "Proverbs 22:6", "verse": "Start children off on the way they should go, and even when they are old they will not turn from it.", "version": "NIV", "hashtag": "#Pr22_6"},
    {"reference": "Genesis 3:1", "verse": "Now the serpent was more crafty than any of the wild animals the LORD God had made. He said to the woman, 'Did God really say, 'You must not eat from any tree in the garden'?'", "version": "NIV", "hashtag": "#Gen3_1"},
    {"reference": "James 1:5", "verse": "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.", "version": "NIV", "hashtag": "#Jas1_5"},
    {"reference": "Hebrews 1:1", "verse": "In the past God spoke to our ancestors through the prophets at many times and in various ways", "version": "NIV", "hashtag": "#Heb1_1"},
    {"reference": "2 John 1:2", "verse": "Because of the truth, which lives in us and will be with us forever:", "version": "NIV", "hashtag": "#IIJn1_2"},
    {"reference": "John 17:3", "verse": "Now this is eternal life: that they know you, the only true God, and Jesus Christ, whom you have sent.", "version": "NIV", "hashtag": "#John17_3"},
    {"reference": "Luke 16:19", "verse": "'There was a rich man who was dressed in purple and fine linen and lived in luxury every day.'", "version": "NIV", "hashtag": "#Luke16_19"},
    {"reference": "John 5:7", "verse": "'Sir,' the invalid replied, 'I have no one to help me into the pool when the water is stirred. While I am trying to get in, someone else goes down ahead of me.'", "version": "NIV", "hashtag": "#John5_7"},
    {"reference": "John 8:31", "verse": "To the Jews who had believed him, Jesus said, 'If you hold to my teaching, you are really my disciples.'", "version": "NIV", "hashtag": "#John8_31"},
    {"reference": "Luke 1:4", "verse": "So that you may know the certainty of the things you have been taught.", "version": "NIV", "hashtag": "#Luke1_4"},
    {"reference": "Revelation 3:20", "verse": "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.", "version": "NIV", "hashtag": "#Rev3_20"},
    {"reference": "Ephesians 2:8", "verse": "For it is by grace you have been saved, through faith – and this is not from yourselves, it is the gift of God", "version": "NIV", "hashtag": "#Eph2_8"},
    {"reference": "John 3:36", "verse": "Whoever believes in the Son has eternal life, but whoever rejects the Son will not see life, for God’s wrath remains on them.", "version": "NIV", "hashtag": "#John3_36"}
]