hindu_quotes = [
    "Most humbly we bow to You, O Supreme Lord. At Your command moves the mighty wheel of time. You are eternal, and beyond eternity. (Artharva Veda)",
    "The one who loves all intensely begins perceiving in all living beings a part of himself. He becomes a lover of all, a part and parcel of the Universal Joy. He flows with the stream of happiness, and is enriched by each soul. (Yajur Veda)",
    "The human body is the temple of God. One who kindles the light of awareness within gets true light. The sacred flame of your inner shrine is constantly bright. The experience of unity is the fulfillment of human endeavors. The mysteries of life are revealed. (Rig Veda)",
    "Sing the song of celestial love, O singer! May the divine fountain of eternal grace and joy enter your soul. May Brahma, (the Divine One), Pluck the strings of your inner soul with His celestial fingers, And feel His own presence within. Bless us with a divine voice That we may tune the harp-strings of our life To sing songs of Love to you. (Rig Veda)",
    "Of everything he is the inmost Self. He is the truth; he is the Self supreme. (Chandogya Upanishad)",
    "Meditating on the lotus of your heart, in the center is the untainted; the exquisitely pure, clear, and sorrowless; the inconceivable; the unmanifest, of infinite form; blissful, tranquil, immortal; the womb of Brahma. (Kaivalyopanishad)",
    "Those in whose hearts OM reverberates Unceasingly are indeed blessed And deeply loved as one who is the Self. The all-knowing Self was never born, Nor will it die. Beyond cause and effect, This Self is eternal and immutable. When the body dies, the Self does not die. (Katha Upanishad)",
    "The whole mantram AUM Indivisible, interdependent, Goes on reverberating in the mind. Established in this cosmic vibration, The sage goes beyond fear, decay, and death To enter into infinite peace. (Prashna Upanishad)",
    "O Almighty! You are the infinite; the universe is also infinite! From infinite the infinite has come out! Having taken infinite out of the infinite, the infinite remains! O Almighty! May there be Peace! Peace! Everywhere! (Ishawashya Upanishad)",
    "O seeker, know the true nature of your soul, and identify yourself with it completely. O Lord, (may we attain) the everlasting consciousness of Supreme Light and Joy. May we resolve to dedicate our life to the service of humankind, and uplift them to Divinity. (Yajur Veda)",
    "O Brahma, lead us from the unreal to the real. O Brahma, lead us from darkness to light. O Brahma, lead us from death to immortality. Shanti, Shanti, Shanti, Om. (Brhadaranyaka Upanishad)",
    "Look to this day, for it is life, the very breath of life. In its brief course lie all the realities of your existence; the bliss of growth, the glory of action, the splendor of beauty. For yesterday is only a dream, and tomorrow is but a vision. But today, well lived, makes every yesterday a dream of happiness, and every tomorrow a vision of hope. Look well, therefore, to this day. (Ancient Sanskrit)",
    "The highest Self, all endless bliss, the unconditioned limitless consciousness, being realized, whether through the great texts, or through Yoga, in all experience whatever—let one lose himself in the ecstasy of Realization, for he has forever lost all touch with bondage of every description. (Svarajyasiddhi)",
    "A particle of Its bliss supplies the bliss of the whole universe. Everything becomes enlightened in Its light. All else appears worthless after a sight of that essence. I am indeed of this Supreme Eternal Self. (Vijnanananka)",
    "The knower catches in the ecstasy of his heart the full light of that Brahman (that Divine Essence) which is indescribable—all pure bliss, incomparable, transcending time, ever free, beyond desire. (Vivekachudamani)",
    "Bright but hidden, the Self dwells in the heart. Everything that moves, breathes, opens, and closes Lives in the Self. He is the source of love And may be known through love but not through thought He is the goal of life. Attain this goal! (Mundaka Upanishad)",
    "All is change in the world of the senses, But changeless is the supreme Lord of Love. Meditate on him, be absorbed by him, Wake up from this dream of separateness. (Shvetashvatara Upanishad)",
    "O mysterious and incomprehensible Spirit! In the depths of my heart, there is only You—You, for all time."
]


# marathi_quotes = {
#     "माझा जन्म कुठे व्हावा, कोणत्या जाती धर्मात व्हावा, आई वडील कसे असावेत, हे माझ्या हाती नव्हते, त्यामुळे त्याबद्दल तक्रार करत बसण्या ऐवजी मी निसर्गाने मला दिलेल्या क्षमतांचा सकारात्मक वापर करून माझे जीवन नक्कीच सुखी करू शकतो.",
#     "कधीतरी मला कोणत्या तरी प्रकारचे दु:ख मिळणार आहे याची जाणीव ठेऊन, मी माझ्या आसपासच्या माणसांची जमेल तशी मदत केली पाहिजे",
#     "मी स्त्री व्हावे कि पुरुष, काळा कि गोरा, माझ्या शरीराची ठेवण, सर्व अवयव ठीकठाक असणे , हे देखील माझ्या हाती नव्हते मात्र जे काही मिळालेय त्याची निगा राखणे, योग्य ती काळजी घेणे, हे माझ्या हाती आहे",
#     "हे विश्व मी निर्माण केलेले नाही. किंवा हे विश्व कसे असले पाहिजे, या माझ्या मताला देखिल काही किंमत नाही. तेव्हा, हे असे का ? , ते तसे का ?, असे का नाही? वैगेरे प्रश्न विचारत राहून वैताग्ण्या ऐवजी, जे चूक आहे, अयोग्य आहे ते किमान मी तरी करणार नाही हे मला ठरवता येईल, हे हि नसे थोडके!",
#     "आज जरी यश, सुख, समृद्धी माझ्या पायाशी लोळण घेत असली, तरी उद्या किंवा कधीही नष्ट होऊ शकते याची सतत जाणीव ठेऊन, मी अहंकाराला दूर ठेवले पाहिजे",

#     "उत्तम गुण तितुके घ्यावे !घेऊन जनास शिकवावे !उदंड समुदाय करावे !परी गुप्तरूपें !!",
#     "वाट पुसल्याविण जाउ नये। फळ ओळखल्याविण खाऊ नये॥ पडिली वस्तु घेऊ नये। येकायेकी॥",
#     "विचारेविण बोलो नये। विवंचनेविण चालो नये॥ मर्यादेविण हालो नये। काही येक॥",
#     "प्रीतीविण रुसो नये। चोरास वोळखी पुसो नये॥ रात्री पंथ क्रमु नये। येकायेकी॥",
#     "जनी आर्जव तोडु नये। पापद्रव्य जोडू नये॥ पुण्यमार्ग सोडू नये। कदाकाळी॥",
#     "वक्तयास खोदु नये। ऐक्यतेशी फोडू नये॥ विद्या-अभ्यास सोडू नये। काही केल्या॥",
#     "तोंडाळासी भांडो नये। वाचाळासी तंडो नये॥ संतसंग खंडु नये। अंतर्यामी॥",
#     "अति क्रोध करु नये। जिवलगांस खेदु नये॥ मनी वीट मानु नये। शिकवणेचा॥",
#     "क्षणाक्षणा रुसो नये। लटिका पुरुषार्थ बोलो नये॥ केल्याविण सांगो नये। आपुला पराक्रमु॥",
#     "आळसे सुख मानू नये। चाहाडी मनास आणू नये॥ शोधल्याविण करू नये। कार्य काही॥",
#     "सुखा आंग देऊ नये। प्रेत्न पुरुषे सांडू नये॥ कष्ट करि त्रासो नये। निरंतर॥",
#     "कोणाचा उपकार घेउ नये। घेतला तरी राखो नये॥ परपीडा करु नये। विश्वासघात॥",
#     "शोच्येविण असो नये। मळिण वस्त्र नेसो नये॥ जाणारास पसो नये। कोठे जातोस म्हणऊनी॥",
#     "सत्यमार्ग सांडू नये। असत्य पंथे जाउ नये॥ कदा अभिमान घेउ नये। असत्याचा॥",
#     "अपकीर्ती ते सांडावी। सत्कीर्ती वाढवावी॥ विवेके दृढ धरावी। वाट सत्याची॥"

#     "आले संत घरी तरी काय बोलुन शिणवावे ऊस गोड लागला म्हणून काय मुळासहीत खावे प्रीतीचा पाहुणा झाला म्हणून काय फार दिवस रहावे गावचा पाटील झाला म्हणून काय गावच बुडवावे अरे कृष्णा अरे कान्हा मनरंजन मोहना",
#     "देव अंगी आला म्हणून काय भलतेच बोलावे चंदन शीतळ झाले म्हणून काय उगळुनिया प्यावे भगवी वस्‍त्रे केली म्हणून काय जगच नाडावे आग्या विंचू झाला म्हणून काय कंठीच कवळावे अरे कृष्णा अरे कान्हा मनरंजन मोहना",
#     "परस्‍त्री सुंदर झाली म्हणून काय बळेची ओढावी सुरी सोन्याची झाली म्हणून काय उरीच मारावी सुरी सोन्याची झाली म्हणून काय उरीच मारावी मखमली पैजार झाली म्हणून काय शिरीच बांधावी अरे कृष्णा अरे कान्हा मनरंजन मोहना",
#     "सद्गुरू सोयरा झाला म्हणून काय आचार बुडवावा नित्य देव भेटला म्हणून काय जगाशी दावावा घरचा दिवा झाला म्हणून काय आढ्याशी बांधावा एका जनार्दनी ह्मणे हरी हा गुप्‍तची ओळखावा अरे कृष्णा अरे कान्हा मनरंजन मोहना"

#     "अरे अडाण्याला शिक्षण द्यावं, बेघरांना घर द्यावं, रंजल्या – गांजल्याची सेवा करावी, मुक्या प्राण्यावर दया करावी… बापहो देव यांच्यात राहतो बापहो देव देवळात राहत नाही… देव आपल्या मनात राहतो… देवळात फक्त पुजा-याचे पोट राहते !!",
#     "एका परमेश्वराशिवाय उगीच नाना देवतांची अनेकत्वाने पूजा करणे म्हणजे आपले प्रेम व्यभिचारी बनवून शुद्ध भावनेचा नाश करणे होय.",
#     "ईश्वराची कृपा धन, ऐश्वर्य, संतती इत्यादि असण्यावर अवलंबून नसून ती सद्विचाराच्या वर्तनावरच अवलंबून असते.",
#     "संगीत किंवा भजन आपल्या हृदयेंद्रियाला सुख देऊ शकत नाही आणि दुसऱ्याच्या मदतीवर अवलंबून असते, त्याला खरे संगीत अथवा भजन म्हणता येत नसून, ती एक लोकंना प्रसन्न करण्याची कला आहे.",
#     "राष्ट्रदेवतेच्या योग्यतेसमोर लोकांच्या आपापल्या लाखों देवता मला सूर्यासमोर गणल्या जाणाऱ्या काजव्याप्रमाणे वाटतात, पण प्रत्येक देवतेचे महत्व त्यांच्या त्यांच्या स्थानी विशेष असणे हे एक मनुष्याच्या स्वार्थीपणाचेच द्योतक असते.",
#     "जे लोक आपत्तीला तोंड देण्याची हिंमत ठेवीत नाहीत, ते भक्ती करुनही मरणाला जिकू शकत नाहीत. जे मरणाला जिंकु शकत नाहीत, ते पुरुष ईश्वराचे भक्त होऊच शकत नाहीत.",
#     "मरणास भिऊन रडत बसण्यापेक्षा मरणे अमर कसे होईल याची चिंता करणे बरे असते.",
#     "मनुष्याने आपल्या सद्विचाराला (विवेकबुद्धीला) व ईश्वराला सदैव भ्याले पाहिजे, परंतु अन्याय आणि दुष्टतेला कधी न भिता हाकून दिले पाहिजे.",
#     "प्रसंगी मार खाऊनही आपली सत्यनिष्ठा व धैर्य न सोडणे याला मार देणणाऱ्यापेक्षाही धाडस ठेवावे लागते, म्हणूनच हिसेंपेक्षा अहिंसेची किंमत अधिक मानली जात असते.",
#     "ताकदवान तो नसतो की, जो दुसऱ्याला खाली पाडतो. तोच ताकदवान खरा की, जो पडलेल्याला उचलून नीतिपथावर आणतो.",
#     "आपली शत्रुविषयीही उत्तम बुद्धी ठेवा त्याने ईश्वराजवळ तुमची कदर होईल.",
#     "जे लोक तुम्हांला अलग फेकतात, त्यांच्याशी तुम्ही मिळून वागण्याची बुद्धी ठेवा. जे लोक तुमच्याशी वाईट वागतील, त्यांच्याशी तुम्ही सरळ वागा म्हणजे प्रभू तुमच्याकरिता त्यांना दंड न देता दोस्त करुन घेईल.",
#     "आपल्या शत्रूचाही कोणाकडून होत असलेला अयोग्य अपमान सहन करणे वीराचे कार्य नव्हे. शत्रूची अयोग्य फजीती नेत्राने पाहून समाधान मानणे हे नीचाचे काम आहे.",
#     "शत्रू आणि मित्र हा भेदभाव कार्यातच समजणे व इतर प्रसंगी दोघांनाही आपल्यासमान पाहणे, हेच शूर लोकांचे लक्षण असते.",
#     "आपत्तीच्या जाळीतून करुण हाक ऐकू येत असता प्राणाची पर्वा न करुन धडाडीने मदत करणारे वीरच खरे वीर समजले जात असतात.",
#     "मनुष्य गुणाने उत्तम असला म्हणजे कुरुपही रुपवान दिसत असतो.",
#     "आपल्याजवळ असलेल्या कोणत्याही वस्तूवर कार्याशिवाय अती प्रेम करणे, म्हणजे उगीच आपली वृत्ती गुलाम करुन शेवटी भुतांच्या हाती प्राण देणेच होय.",
#     "कोणत्याही माणसाची प्रेतयात्रा चालली असता निदान पाच पावले तरी त्याच्यामागून चालू लागा व नंतर आपले काम करा ही त्या रथीची इभ्रत आहे."
#     "मोठ्या गुन्हेगारांपैकी ते लोक असतात, जे आपल्या वडिलांची सत्य आज्ञाही मानीत नसतात आणि मोठ्यांची मने दुखवितात; खोटीच शपथ सदा घेतात नि खोटीच साक्ष लोभास्तव देतात.",
#     "मनुष्याचा स्वभाव एखाद्या प्रसंगानेच उघडा पडत असतो.",
#     "तेच लोक सज्जन असतात, ज्यांना उत्तम कामाविषयी खुशी आणि वाईट कामाचे दुःख होते.",
#     "खरा स्वयंसेवक तोच की, ज्यावर लोक आपली कौटुंबिक मालमत्ता सोपवण्याएवढा भरवसा ठेवू शकतात नि तसे करिताना नि:शंक राहतात.",
#     "शस्त्रे घर्षणाने चमकतात आणि शूर संघर्ष प्रसंगानीच चमकत असतो.",
#     "धाडसाची तयारी प्रसंगांनीच लौकर वाढत असते, केवळ छाती मोठी करुन नव्हे.",
#     "लक्षावधी रुपये देत असताही जो लाचलुचपतीच्या मोहाने आपली न्यायबुद्धी गहाण ठेवून सत्य पक्ष विसरत नाही, तोच पुरुष वीरांच्या मालिकेत बसवण्यास योग्य असतो.",
#     "प्रयत्नशील व वीर पुरुषास हा समस्त संसार गुलाबाच्या फुलांच्या ताटव्यासारखा आल्हादकारक सुगंध देणारा वाटत असतो.",
#     "लोकांकडून नेहमी सन्मान घेऊ इच्छिणारी माणसे ऐन प्रसंगी अपमानास पात्र होतात. याकरिता आपला उगीच मान व्हावा असे चिंतू नका आणि सर्वाशी समान भावनेने वागा.",
#     "देहापेक्षा कर्तव्याचा मान लाखोपटीने उत्तम असतो आणि चिरंतर ही (अमर) असतो.",
#     "पुढे सरकाल तर सेवेकरिता आणि मागे हटाल तर मानाकरिता (सन्मानप्रसंगी); असे झाले की लोकमित्र निश्चयाने व्हाल."

#     "घासावा शब्द | तासावा शब्द |",
#     "तोलावा शब्द | बोलण्या पूर्वी ||",
#     "शब्द हेचि कातर | शब्द सुईदोरा",
#     "बेतावेत शब्द | शास्त्राधारे ||",
#     "बोलावे मोजके | नेमके ,खमंग ,खमके |",
#     "ठेवावे भान | देश ,काळ ,पात्राचे",
#     "बोलावे बरे | बोलावे खरे |",
#     "कोणाच्याही मनावर | पाडू नये चरे ||",
#     "कोणाचेही वर्म | व्यंग आणि बिंग |",
#     "जातपात धर्म | काढूच नये ||",
#     "थोडक्यात समजणे | थोडक्यात समजावणे |",
#     "मुद्देसुद बोलणे | हि संवाद कला",
#     "शब्दांमध्ये झळकावी | ज्ञान , कर्म ,भक्ती |",
#     "स्वानुभवातून जन्मावा | प्रत्येक शब्द ||",
#     "शब्दां मुळे दंगल | शब्दां मुळे मंगल |",
#     "शब्दांचे हे जंगल | जागृत राहावं ||",
#     "जीभेवरी ताबा | सर्वासुखदाता |",
#     "पाणी ,वाणी ,नाणी | नासू नये",
#     "शुध्द बीजापोटी ।",
#     "फळे रसाळ गोमटी ।।",
#     "मन करा रे प्रसन्न ।",
#     "सर्व सिद्धीचे कारण ।",
#     "अज्ञानाच्या पोटी,",
#     "अवघीच फजिती",
#     "तुम्ही मुलाबाळांसाठी खुप काही करता.",
#     "पण गोरगरिबांसाठी देखील तसच करत चला",
#     "आपण चंदन असल्याची घोषणा",
#     "चंदनाला करावी लागत नाही",
#     "माणसाने थोडातरी परोपकार करावा.",
#     "अनाथ अपंगाची सेवा करा.",
#     "जे जाणुनबुजून चुकत असतील त्यांची फजिती करा.",
#     "साधु-संत येती घरा । तोचि दिवाळी दसरा ।",
#     "चांगले मित्र हेच भाग्याचं लक्षण",
#     "दया, क्षमा, शांती । तेथे देवाची वस्ती ।।",
#     "सुख पाहता जवापाडे । दुःख पर्वताएवढे ।।",
#     "जया अंगी मोठेपण तया यातना कठीण",
#     "बहुमत चुकीचे असल्यास कधीही स्वीकारू नये",
#     "सत्य आणि असत्याचा शोध घेणाऱ्यांनी आपल्या मनाचा कौल मानावा.",
#     "प्रस्थापित पढिक विद्वान हे ज्ञानाचे आंधळे भारवाहक आहेत",
#     "लहानपण देगा देवा । मुंगी साखरेचा रवा ।।",
#     "ठेविले अनंती तैसेचि राहावे । चित्ती असुद्या समाधान",
#     "दुर्जनांचा मान मुळीच ठेऊ नये. उलट पद्धतशीरपणे अवमान करावा",
#     "खरा ज्ञानी लोकांना तारतो.",
#     "तेथे कोणाचे चालेना, आले देवाजीच्या मना || धृ || हरिचंद्र तारामती वाहे डोंबा घरी पाणी || १ || पांडवांचा सहकारी, राज्या वरोनी केले दुरी || २ || तुका म्हणे उगेची रहा, होईल ते सहज पहा || ३ ||"
# }
